name = "Mkk project"
prefix = "mkk"
mainprefix = "x"

[version]
path = "addons/sys/script_version.hpp"
git_hash = 0

[files]
exclude = ["*.md"]
include = ["./include", "mod.paa"]

[hemtt.build]
optional_mod_folders = false # Default: true

[hemtt.release]
sign = false    # Default: true
archive = false # Default: true
